<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="mkrishnan" name="com.avlview.app.testcases.ForgotPasswordPageTest" tests="9" failures="1" timestamp="08 Jan 2019 09:13:41 GMT" time="172.723" errors="0">
  <testcase name="validateForgotPasswordPageExistTest" time="17.025" classname="com.avlview.app.testcases.ForgotPasswordPageTest">
    <skipped/>
  </testcase> <!-- validateForgotPasswordPageExistTest -->
  <testcase name="validateForgotPasswordPageExistTest" time="18.815" classname="com.avlview.app.testcases.ForgotPasswordPageTest">
    <failure type="java.lang.AssertionError" message="expected [Forgot your password1?] but found [Forgot your password?]">
      <![CDATA[java.lang.AssertionError: expected [Forgot your password1?] but found [Forgot your password?]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.avlview.app.testcases.ForgotPasswordPageTest.validateForgotPasswordPageExistTest(ForgotPasswordPageTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateForgotPasswordPageExistTest -->
  <testcase name="validateClientLogoExistTest" time="13.271" classname="com.avlview.app.testcases.ForgotPasswordPageTest"/>
  <testcase name="validateApplogoExistTest" time="13.201" classname="com.avlview.app.testcases.ForgotPasswordPageTest"/>
  <testcase name="validateBacktoLoginExistTest" time="23.939" classname="com.avlview.app.testcases.ForgotPasswordPageTest"/>
  <testcase name="validateBacktoLoginClickTest" time="20.050" classname="com.avlview.app.testcases.ForgotPasswordPageTest"/>
  <testcase name="validateNouserClickTest" time="19.016" classname="com.avlview.app.testcases.ForgotPasswordPageTest"/>
  <testcase name="validateInvaliduserClickTest" time="27.587" classname="com.avlview.app.testcases.ForgotPasswordPageTest"/>
  <testcase name="validateValiduserClickTest" time="19.819" classname="com.avlview.app.testcases.ForgotPasswordPageTest"/>
</testsuite> <!-- com.avlview.app.testcases.ForgotPasswordPageTest -->
